"""stdlib-only test suite for the lee-espanol render pipeline.

Covers .ai/skills/render/render.py: golden/idempotency regression against the
on-disk story pages, spanish_cardinal / russian_cardinal correctness, a
tokenize/detokenize round trip, the shared sentence-mark end/pause classifier,
and a repo-wide --lint no-errors check.

Run from the project root:
    py -m unittest discover tests -v

No pytest, no pip dependencies -- unittest + stdlib only.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import shutil
import tempfile
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = TESTS_DIR.parent
RENDER_PY = PROJECT_ROOT / ".ai" / "skills" / "render" / "render.py"
STORIES_DIR = PROJECT_ROOT / "stories"


def _load_render_module():
    """Import render.py by path (no __init__.py / package on this path)."""
    spec = importlib.util.spec_from_file_location("lee_render", RENDER_PY)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


render = _load_render_module()


def _story_dirs_with_all_inputs() -> list[Path]:
    """NN-slug/ dirs on disk that have story.md + enrichment.toml + index.html --
    the set apply_enrichment can actually be re-run against."""
    out: list[Path] = []
    if not STORIES_DIR.is_dir():
        return out
    for sub in sorted(STORIES_DIR.iterdir()):
        if not sub.is_dir():
            continue
        if (
            (sub / "story.md").exists()
            and (sub / "enrichment.toml").exists()
            and (sub / "index.html").exists()
        ):
            out.append(sub)
    return out


class GoldenIdempotencyTests(unittest.TestCase):
    """Centerpiece test. All 21 story pages on disk were just regenerated by this
    exact code and verified -- so they are valid golden outputs. For each story,
    copy it to a throwaway directory, re-run apply_enrichment on the copy, and
    assert the result is byte-identical to the real on-disk index.html. This
    simultaneously proves determinism, idempotency, and guards against
    regressions in render.py.

    The throwaway copy is made under tests/ (via tempfile, auto-cleaned) rather
    than the system temp dir: apply_enrichment ends with
    `out_path.relative_to(ROOT)` for a status print, and ROOT is render.py's
    real project root -- the copy must stay a subpath of it or that call raises.
    apply_enrichment only ever writes its own out_path (the copy's index.html);
    everything else it touches (STORIES_DIR, for "new words" bookkeeping against
    earlier stories) is read-only. The copy keeps the original NN-slug directory
    name so seq-number ordering and self-exclusion from "earlier stories" still
    work correctly.
    """

    def test_golden_idempotency_for_every_story(self):
        story_dirs = _story_dirs_with_all_inputs()
        self.assertTrue(
            story_dirs,
            "expected at least one stories/NN-slug/ with story.md+enrichment.toml+index.html",
        )

        for story_dir in story_dirs:
            slug = story_dir.name
            with self.subTest(slug=slug):
                original_html = (story_dir / "index.html").read_bytes()

                with tempfile.TemporaryDirectory(dir=str(TESTS_DIR)) as tmp_root:
                    tmp_story_dir = Path(tmp_root) / slug
                    shutil.copytree(story_dir, tmp_story_dir)

                    # apply_enrichment prints progress lines (some non-ASCII, e.g.
                    # an em dash / warning glyph) -- swallow them so the run stays
                    # quiet and never risks a console-encoding error.
                    buf = io.StringIO()
                    with contextlib.redirect_stdout(buf):
                        render.apply_enrichment(tmp_story_dir)

                    rendered_html = (tmp_story_dir / "index.html").read_bytes()

                self.assertEqual(
                    rendered_html,
                    original_html,
                    f"{slug}: re-rendering a fresh copy did not reproduce the "
                    f"on-disk index.html byte-for-byte (determinism/idempotency "
                    f"regression)",
                )


class SpanishCardinalTests(unittest.TestCase):
    """spanish_cardinal(n) against independently-derived correct Spanish, not
    against whatever render.py happens to output. A mismatch here is a real bug
    to report, not something this suite should paper over."""

    CASES = [
        (0, "cero"),
        (1, "uno"),
        (7, "siete"),
        (12, "doce"),
        (21, "veintiuno"),
        (100, "cien"),
        (101, "ciento uno"),
        (412, "cuatrocientos doce"),
        (500, "quinientos"),          # irregular hundred, not "cincocientos"
        (999, "novecientos noventa y nueve"),
        (1000, "mil"),                # not "un mil"
        (7012, "siete mil doce"),
        (2031, "dos mil treinta y uno"),
        # apocope inside a compound multiplier: uno/veintiuno -> un/veintiun
        # when immediately followed by "mil".
        (21000, "veintiún mil"),
        (31000, "treinta y un mil"),
    ]

    def test_spanish_cardinal(self):
        for n, expected in self.CASES:
            with self.subTest(n=n):
                self.assertEqual(render.spanish_cardinal(n), expected)

    def test_es_apocope_edge_cases(self):
        self.assertEqual(render._es_apocope("uno"), "un")
        self.assertEqual(render._es_apocope("veintiuno"), "veintiún")
        self.assertEqual(render._es_apocope("treinta y uno"), "treinta y un")

    def test_es_feminine_edge_cases(self):
        self.assertEqual(render._es_feminine("uno"), "una")
        self.assertEqual(render._es_feminine("veintiuno"), "veintiuna")
        self.assertEqual(render._es_feminine("quinientos"), "quinientas")


class RussianCardinalTests(unittest.TestCase):
    """russian_cardinal(n): nominative, masculine-baseline citation form, except
    thousands (a feminine noun) which correctly triggers odin/dva -> odna/dve."""

    CASES = [
        (0, "ноль"),
        (1, "один"),
        (7, "семь"),
        (12, "двенадцать"),
        (21, "двадцать один"),
        (100, "сто"),
        (101, "сто один"),
        (412, "четыреста двенадцать"),
        (999, "девятьсот девяносто девять"),
        (1000, "одна тысяча"),        # тысяча is feminine: один -> одна
        (7012, "семь тысяч двенадцать"),
        (2031, "две тысячи тридцать один"),  # два -> две before тысячи
    ]

    def test_russian_cardinal(self):
        for n, expected in self.CASES:
            with self.subTest(n=n):
                self.assertEqual(render.russian_cardinal(n), expected)


class TokenizeDetokenizeRoundTripTests(unittest.TestCase):
    """walk_html_body(...) followed by detokenize(...) must recover the exact
    original body markup. Covers: plain words, a matched phrase/idiom, a plain
    number, dot-grouped thousands (7.012), an end ellipsis at end-of-segment, a
    mid-sentence pause ellipsis followed by a lowercase word, and designer
    inline markup (<em>) preserved verbatim."""

    def test_round_trip_recovers_original_body(self):
        words = {
            "casa": {"tr": "TR_CASA", "pos": "n", "lemma": "casa"},
            "parecia": {"tr": "TR_PARECIA", "pos": "v"},
            "son": {"tr": "TR_SON", "pos": "v"},
            "silencio": {"tr": "TR_SILENCIO", "pos": "n"},
        }
        phrases = [{"form": "de repente", "tr": "TR_DE_REPENTE", "pos": "idiom"}]
        sentences = [{"tr": "S1"}, {"tr": "S2"}, {"tr": "S3"}]
        numbers: dict = {}

        content = (
            "<p>La casa <em>de repente</em> parecia tener 7.012 anos. "
            "Bip... bip: son 12.</p>"
            "<p>Al final llego el silencio...</p>"
        )

        phrase_idx = render.build_phrase_index(words, phrases)
        new_body, missed, used = render.walk_html_body(
            content, words, phrase_idx, sentences, numbers
        )

        # Sanity: tokenization actually happened and the number/idiom paths fired.
        self.assertIn('<span class="w"', new_body)
        self.assertIn('<em><span class="w"', new_body)  # phrase inside designer markup
        self.assertIn('data-lemma="siete mil doce"', new_body)  # 7.012 auto-cardinal
        self.assertEqual(used, 3)  # "anos.", "12." and the trailing "..." are ends

        recovered = render.detokenize(new_body)
        self.assertEqual(recovered, content)


class SentenceMarkClassificationTests(unittest.TestCase):
    """term_run_is_end(...) is the single shared classifier for both rendering
    and --lint. Exercise its documented rules directly."""

    def test_ellipsis_before_uppercase_word_is_end(self):
        text = "...  Cada"
        self.assertTrue(render.term_run_is_end(text, 3))

    def test_ellipsis_before_lowercase_word_is_pause(self):
        text = "... bip"
        self.assertFalse(render.term_run_is_end(text, 3))

    def test_interrobang_run_is_a_single_mark(self):
        matches = list(render.TERM_RUN_RE.finditer("?!"))
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].group(), "?!")

    def test_digits_are_never_terminators(self):
        # "7.012" must tokenize as ONE number span; NUM_RE's strict dot-grouping
        # is tried before TERM_RUN_RE, so the embedded dot is never split off.
        take_sent = lambda: {}
        s_used = [0]
        cur_si = lambda: s_used[0]
        rendered, missed = render.tokenize_text_segment(
            "7.012", {}, [], take_sent, cur_si, {}
        )
        self.assertEqual(rendered.count('<span class="w"'), 1)
        self.assertNotIn('<span class="s"', rendered)
        self.assertEqual(missed, [])

    def test_terminator_run_at_end_of_text_is_end(self):
        text = "final..."
        self.assertTrue(render.term_run_is_end(text, len(text)))


class LintCleanRepoTests(unittest.TestCase):
    """The repo is currently all-green under --lint; keep it that way."""

    def test_lint_story_has_no_errors_for_every_story(self):
        slugs = render.disk_slugs()
        self.assertTrue(slugs, "expected at least one story on disk")
        for slug in slugs:
            with self.subTest(slug=slug):
                errors, warnings, infos = render.lint_story(slug)
                self.assertEqual(errors, [], f"{slug}: lint errors: {errors}")


class AnchorConsistencyTests(unittest.TestCase):
    """Every 'Palabras nuevas' deep link on every story page must land on a
    vocabulario.html entry with the SAME lemma. This is the regression net for
    the accent-collision bug (el/él, si/sí, sonar/soñar all slugify to the same
    base): anchors are assigned with -2 suffixes in vocabulario.html, and the
    new-words blocks must use the very same assignment, not re-derive their own."""

    def test_new_words_links_hit_matching_vocab_entries(self):
        import html as html_mod
        import re

        vocab = (PROJECT_ROOT / "vocabulario.html").read_text(encoding="utf-8")
        entry_re = re.compile(
            r'<div class="v-entry" id="([^"]+)"[^>]*>\s*'
            r'<span class="v-lemma">([^<]*)</span>'
        )
        vocab_lemma_by_id = {
            m.group(1): html_mod.unescape(m.group(2)) for m in entry_re.finditer(vocab)
        }
        self.assertTrue(vocab_lemma_by_id, "no entries parsed from vocabulario.html")

        link_re = re.compile(
            r'vocabulario\.html#([^"]+)">\s*'
            r'<span class="nw-lemma">([^<]*)</span>'
        )
        checked = 0
        for story_dir in _story_dirs_with_all_inputs():
            text = (story_dir / "index.html").read_text(encoding="utf-8")
            for m in link_re.finditer(text):
                anchor, lemma = m.group(1), html_mod.unescape(m.group(2))
                with self.subTest(slug=story_dir.name, lemma=lemma):
                    self.assertIn(anchor, vocab_lemma_by_id,
                                  f"dead anchor #{anchor} for lemma {lemma!r}")
                    self.assertEqual(vocab_lemma_by_id[anchor], lemma,
                                     f"#{anchor} points at a different entry")
                checked += 1
        self.assertGreater(checked, 100, "suspiciously few new-words links checked")


class SplitSentencesTests(unittest.TestCase):
    """split_sentences must mirror the tokenizer's END/pause/number rules exactly
    (it powers --prefill sentence stubs and --lint's drift check)."""

    def test_pause_runs_stay_inside_their_sentence(self):
        text = "Bip... bip... bip... Cada cinco segundos."
        self.assertEqual(render.split_sentences(text),
                         ["Bip... bip... bip...", "Cada cinco segundos."])

    def test_closing_quote_attaches_to_its_sentence(self):
        text = 'Ella dice: "Hola." Adios.'
        self.assertEqual(render.split_sentences(text),
                         ['Ella dice: "Hola."', "Adios."])

    def test_dot_grouped_number_is_not_a_boundary(self):
        text = "El anno 7.012 fue largo. Fin."
        self.assertEqual(render.split_sentences(text),
                         ["El anno 7.012 fue largo.", "Fin."])

    def test_whitespace_is_normalized(self):
        text = "Una   frase\ncon saltos."
        self.assertEqual(render.split_sentences(text), ["Una frase con saltos."])


class JsPayloadTests(unittest.TestCase):
    def test_script_close_tag_is_escaped(self):
        out = render.js_payload([{"tr": "a</script><b>x"}])
        self.assertNotIn("</script>", out)
        # Still valid JSON semantics: <\/ decodes back to </ in JS.
        self.assertIn("<\\/script>", out)


class _StoriesSandbox:
    """Context manager: point render.STORIES_DIR at a temp dir under tests/."""

    def __init__(self):
        self._tmp = None
        self._orig = None

    def __enter__(self) -> Path:
        self._tmp = tempfile.TemporaryDirectory(dir=str(TESTS_DIR))
        self._orig = render.STORIES_DIR
        render.STORIES_DIR = Path(self._tmp.name)
        return render.STORIES_DIR

    def __exit__(self, *exc):
        render.STORIES_DIR = self._orig
        self._tmp.cleanup()
        return False


_FM = """---
title: "T{n}"
logline: "l"
protagonist: "p"
setting: "s"
date_generated: "2026-07-12"
length_words: "5"
---

"""


class PrefillTests(unittest.TestCase):
    """--prefill drafts enrichment.toml: corpus-known words copied, new words and
    sentence translations stubbed, output must parse as valid TOML."""

    def test_prefill_draft(self):
        with _StoriesSandbox() as stories:
            s1 = stories / "01-uno"
            s1.mkdir()
            (s1 / "story.md").write_text(_FM.format(n=1) + "La casa es azul.\n", encoding="utf-8")
            (s1 / "enrichment.toml").write_text(
                '[words.la]\ntr = "артикль"\npos = "арт."\nlemma = "la"\n'
                '[words.casa]\ntr = "дом"\npos = "сущ."\nlemma = "la casa"\n'
                'grammar = """\n**casa** — сущ. `ж. р.`\n"""\n'
                '[words.es]\ntr = "есть"\npos = "глаг."\nlemma = "ser"\n'
                '[words.azul]\ntr = "синий"\npos = "прил."\nlemma = "azul"\n'
                '[[sentences]]\ntext = "La casa es azul."\ntr = "Дом синий."\n',
                encoding="utf-8",
            )
            s2 = stories / "02-dos"
            s2.mkdir()
            (s2 / "story.md").write_text(
                _FM.format(n=2) + "La casa es roja. Es grande.\n", encoding="utf-8")

            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                render.prefill(s2, force=False)

            import tomllib
            raw = (s2 / "enrichment.toml").read_text(encoding="utf-8")
            data = tomllib.loads(raw)

            # Known words prefilled with their corpus entries (multiline grammar survives).
            self.assertEqual(data["words"]["casa"]["tr"], "дом")
            self.assertIn("**casa**", data["words"]["casa"]["grammar"])
            # New words stubbed empty.
            self.assertEqual(data["words"]["roja"]["tr"], "")
            self.assertEqual(data["words"]["grande"]["tr"], "")
            # One sentence stub per END mark, with extracted text and empty tr.
            self.assertEqual([s["text"] for s in data["sentences"]],
                             ["La casa es roja.", "Es grande."])
            self.assertTrue(all(s["tr"] == "" for s in data["sentences"]))

            # Refuses to overwrite without --force.
            with self.assertRaises(render.RenderError):
                render.prefill(s2, force=False)

    def test_toml_str_round_trips(self):
        import tomllib
        cases = [
            'plain',
            'with "quotes" and \\backslash',
            'multi\nline — **bold** `code [[x]]`\n',
        ]
        for s in cases:
            with self.subTest(s=s):
                parsed = tomllib.loads(f"v = {render._toml_str(s)}")["v"]
                self.assertEqual(parsed, s)


class LintQualityTests(unittest.TestCase):
    """The empty-tr error (catches --prefill stubs left unfilled) and the
    sentence-text drift warning."""

    def test_empty_tr_is_an_error(self):
        with _StoriesSandbox() as stories:
            s1 = stories / "01-uno"
            s1.mkdir()
            (s1 / "story.md").write_text(_FM.format(n=1) + "Sol rojo.\n", encoding="utf-8")
            (s1 / "enrichment.toml").write_text(
                '[words.sol]\ntr = ""\npos = "сущ."\nlemma = "el sol"\n'
                '[words.rojo]\ntr = "красный"\npos = "прил."\nlemma = "rojo"\n'
                '[[sentences]]\ntext = "Sol rojo."\ntr = "Красное солнце."\n',
                encoding="utf-8",
            )
            errors, warnings, infos = render.lint_story("01-uno")
            self.assertTrue(any("empty tr" in e for e in errors), errors)

    def test_sentence_text_drift_is_a_warning(self):
        with _StoriesSandbox() as stories:
            s1 = stories / "01-uno"
            s1.mkdir()
            (s1 / "story.md").write_text(_FM.format(n=1) + "Sol rojo.\n", encoding="utf-8")
            (s1 / "enrichment.toml").write_text(
                '[words.sol]\ntr = "солнце"\npos = "сущ."\nlemma = "el sol"\n'
                '[words.rojo]\ntr = "красный"\npos = "прил."\nlemma = "rojo"\n'
                '[[sentences]]\ntext = "Luna azul brillante."\ntr = "Красное солнце."\n',
                encoding="utf-8",
            )
            errors, warnings, infos = render.lint_story("01-uno")
            self.assertEqual(errors, [], errors)
            self.assertTrue(any("drift" in w for w in warnings), warnings)


if __name__ == "__main__":
    unittest.main()
