"""stdlib-only test suite for the lee-espanol render pipeline.

Covers .ai/skills/render/render.py: golden/idempotency regression against the
on-disk story pages, spanish_cardinal / russian_cardinal correctness, a
tokenize/detokenize round trip, the shared sentence-mark end/pause classifier,
and a repo-wide --lint no-errors check.

Run from the project root:
    py -m unittest discover tests -v

No pytest, no pip dependencies -- unittest + stdlib only.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import shutil
import tempfile
import unittest
from pathlib import Path

TESTS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = TESTS_DIR.parent
RENDER_PY = PROJECT_ROOT / ".ai" / "skills" / "render" / "render.py"
STORIES_DIR = PROJECT_ROOT / "stories"


def _load_render_module():
    """Import render.py by path (no __init__.py / package on this path)."""
    spec = importlib.util.spec_from_file_location("lee_render", RENDER_PY)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


render = _load_render_module()


def _story_dirs_with_all_inputs() -> list[Path]:
    """NN-slug/ dirs on disk that have story.md + enrichment.toml + index.html --
    the set apply_enrichment can actually be re-run against."""
    out: list[Path] = []
    if not STORIES_DIR.is_dir():
        return out
    for sub in sorted(STORIES_DIR.iterdir()):
        if not sub.is_dir():
            continue
        if (
            (sub / "story.md").exists()
            and (sub / "enrichment.toml").exists()
            and (sub / "index.html").exists()
        ):
            out.append(sub)
    return out


class GoldenIdempotencyTests(unittest.TestCase):
    """Centerpiece test. All 21 story pages on disk were just regenerated by this
    exact code and verified -- so they are valid golden outputs. For each story,
    copy it to a throwaway directory, re-run apply_enrichment on the copy, and
    assert the result is byte-identical to the real on-disk index.html. This
    simultaneously proves determinism, idempotency, and guards against
    regressions in render.py.

    The throwaway copy is made under tests/ (via tempfile, auto-cleaned) rather
    than the system temp dir: apply_enrichment ends with
    `out_path.relative_to(ROOT)` for a status print, and ROOT is render.py's
    real project root -- the copy must stay a subpath of it or that call raises.
    apply_enrichment only ever writes its own out_path (the copy's index.html);
    everything else it touches (STORIES_DIR, for "new words" bookkeeping against
    earlier stories) is read-only. The copy keeps the original NN-slug directory
    name so seq-number ordering and self-exclusion from "earlier stories" still
    work correctly.
    """

    def test_golden_idempotency_for_every_story(self):
        story_dirs = _story_dirs_with_all_inputs()
        self.assertTrue(
            story_dirs,
            "expected at least one stories/NN-slug/ with story.md+enrichment.toml+index.html",
        )

        for story_dir in story_dirs:
            slug = story_dir.name
            with self.subTest(slug=slug):
                original_html = (story_dir / "index.html").read_bytes()

                with tempfile.TemporaryDirectory(dir=str(TESTS_DIR)) as tmp_root:
                    tmp_story_dir = Path(tmp_root) / slug
                    shutil.copytree(story_dir, tmp_story_dir)

                    # apply_enrichment prints progress lines (some non-ASCII, e.g.
                    # an em dash / warning glyph) -- swallow them so the run stays
                    # quiet and never risks a console-encoding error.
                    buf = io.StringIO()
                    with contextlib.redirect_stdout(buf):
                        render.apply_enrichment(tmp_story_dir)

                    rendered_html = (tmp_story_dir / "index.html").read_bytes()

                self.assertEqual(
                    rendered_html,
                    original_html,
                    f"{slug}: re-rendering a fresh copy did not reproduce the "
                    f"on-disk index.html byte-for-byte (determinism/idempotency "
                    f"regression)",
                )


class SpanishCardinalTests(unittest.TestCase):
    """spanish_cardinal(n) against independently-derived correct Spanish, not
    against whatever render.py happens to output. A mismatch here is a real bug
    to report, not something this suite should paper over."""

    CASES = [
        (0, "cero"),
        (1, "uno"),
        (7, "siete"),
        (12, "doce"),
        (21, "veintiuno"),
        (100, "cien"),
        (101, "ciento uno"),
        (412, "cuatrocientos doce"),
        (500, "quinientos"),          # irregular hundred, not "cincocientos"
        (999, "novecientos noventa y nueve"),
        (1000, "mil"),                # not "un mil"
        (7012, "siete mil doce"),
        (2031, "dos mil treinta y uno"),
        # apocope inside a compound multiplier: uno/veintiuno -> un/veintiun
        # when immediately followed by "mil".
        (21000, "veintiún mil"),
        (31000, "treinta y un mil"),
    ]

    def test_spanish_cardinal(self):
        for n, expected in self.CASES:
            with self.subTest(n=n):
                self.assertEqual(render.spanish_cardinal(n), expected)

    def test_es_apocope_edge_cases(self):
        self.assertEqual(render._es_apocope("uno"), "un")
        self.assertEqual(render._es_apocope("veintiuno"), "veintiún")
        self.assertEqual(render._es_apocope("treinta y uno"), "treinta y un")

    def test_es_feminine_edge_cases(self):
        self.assertEqual(render._es_feminine("uno"), "una")
        self.assertEqual(render._es_feminine("veintiuno"), "veintiuna")
        self.assertEqual(render._es_feminine("quinientos"), "quinientas")


class RussianCardinalTests(unittest.TestCase):
    """russian_cardinal(n): nominative, masculine-baseline citation form, except
    thousands (a feminine noun) which correctly triggers odin/dva -> odna/dve."""

    CASES = [
        (0, "ноль"),
        (1, "один"),
        (7, "семь"),
        (12, "двенадцать"),
        (21, "двадцать один"),
        (100, "сто"),
        (101, "сто один"),
        (412, "четыреста двенадцать"),
        (999, "девятьсот девяносто девять"),
        (1000, "одна тысяча"),        # тысяча is feminine: один -> одна
        (7012, "семь тысяч двенадцать"),
        (2031, "две тысячи тридцать один"),  # два -> две before тысячи
    ]

    def test_russian_cardinal(self):
        for n, expected in self.CASES:
            with self.subTest(n=n):
                self.assertEqual(render.russian_cardinal(n), expected)


class TokenizeDetokenizeRoundTripTests(unittest.TestCase):
    """walk_html_body(...) followed by detokenize(...) must recover the exact
    original body markup. Covers: plain words, a matched phrase/idiom, a plain
    number, dot-grouped thousands (7.012), an end ellipsis at end-of-segment, a
    mid-sentence pause ellipsis followed by a lowercase word, and designer
    inline markup (<em>) preserved verbatim."""

    def test_round_trip_recovers_original_body(self):
        words = {
            "casa": {"tr": "TR_CASA", "pos": "n", "lemma": "casa"},
            "parecia": {"tr": "TR_PARECIA", "pos": "v"},
            "son": {"tr": "TR_SON", "pos": "v"},
            "silencio": {"tr": "TR_SILENCIO", "pos": "n"},
        }
        phrases = [{"form": "de repente", "tr": "TR_DE_REPENTE", "pos": "idiom"}]
        sentences = [{"tr": "S1"}, {"tr": "S2"}, {"tr": "S3"}]
        numbers: dict = {}

        content = (
            "<p>La casa <em>de repente</em> parecia tener 7.012 anos. "
            "Bip... bip: son 12.</p>"
            "<p>Al final llego el silencio...</p>"
        )

        phrase_idx = render.build_phrase_index(words, phrases)
        new_body, missed, used = render.walk_html_body(
            content, words, phrase_idx, sentences, numbers
        )

        # Sanity: tokenization actually happened and the number/idiom paths fired.
        self.assertIn('<span class="w"', new_body)
        self.assertIn('<em><span class="w"', new_body)  # phrase inside designer markup
        self.assertIn('data-lemma="siete mil doce"', new_body)  # 7.012 auto-cardinal
        self.assertEqual(used, 3)  # "anos.", "12." and the trailing "..." are ends

        recovered = render.detokenize(new_body)
        self.assertEqual(recovered, content)


class SentenceMarkClassificationTests(unittest.TestCase):
    """term_run_is_end(...) is the single shared classifier for both rendering
    and --lint. Exercise its documented rules directly."""

    def test_ellipsis_before_uppercase_word_is_end(self):
        text = "...  Cada"
        self.assertTrue(render.term_run_is_end(text, 3))

    def test_ellipsis_before_lowercase_word_is_pause(self):
        text = "... bip"
        self.assertFalse(render.term_run_is_end(text, 3))

    def test_interrobang_run_is_a_single_mark(self):
        matches = list(render.TERM_RUN_RE.finditer("?!"))
        self.assertEqual(len(matches), 1)
        self.assertEqual(matches[0].group(), "?!")

    def test_digits_are_never_terminators(self):
        # "7.012" must tokenize as ONE number span; NUM_RE's strict dot-grouping
        # is tried before TERM_RUN_RE, so the embedded dot is never split off.
        take_sent = lambda: {}
        s_used = [0]
        cur_si = lambda: s_used[0]
        rendered, missed = render.tokenize_text_segment(
            "7.012", {}, [], take_sent, cur_si, {}
        )
        self.assertEqual(rendered.count('<span class="w"'), 1)
        self.assertNotIn('<span class="s"', rendered)
        self.assertEqual(missed, [])

    def test_terminator_run_at_end_of_text_is_end(self):
        text = "final..."
        self.assertTrue(render.term_run_is_end(text, len(text)))


class LintCleanRepoTests(unittest.TestCase):
    """The repo is currently all-green under --lint; keep it that way."""

    def test_lint_story_has_no_errors_for_every_story(self):
        slugs = render.disk_slugs()
        self.assertTrue(slugs, "expected at least one story on disk")
        for slug in slugs:
            with self.subTest(slug=slug):
                errors, warnings, infos = render.lint_story(slug)
                self.assertEqual(errors, [], f"{slug}: lint errors: {errors}")


if __name__ == "__main__":
    unittest.main()
